version: "3.3"
services:
  app-kaddem:
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/kaddem?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
      - spring.jpa.hibernate.ddl-auto=update
    ports:
      - "8089:8089"
    image: "oumayma170/kaddem:0.0.5"
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:5.7"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=kaddem
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app-kaddem  # S'assurer que l'application est prête avant la collecte des métriques

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus  # S'assurer que Prometheus est prêt avant la visualisation

volumes:
  db:
